### ISSUE TITLE
aiy.vision.models.object_detection_anchors

### ISSUE THREAD

**Issue by di-jabil** [giacomobartoli/vision-kit#3]
Hi thanks a lot for your example. I have a question that would really appreciate your advice on: In a Nov 2018 release, the AIY team made some changes on aiy/vision/models/object_detection.py, they replaced importing aiy.vision.models.object_detection_anchors with loading the anchors from a txt file (https://github.com/google/aiyprojects-raspbian/blob/aiyprojects/src/aiy/vision/models/object_detection.py). Have you tried this new release yet? I would much appreciate your thoughts on the difference between the old importing and the new loading a txt file. Thank you very much

**Comment by giacomobartoli** [comment]
Hi @di-jabil :-)
To be honest I have not tried this new release. What about you?
Maybe this new version could require some quick fix for being able to run the Pikachu Detector, but then it should work.

**Comment by di-jabil** [comment]
Hi @giacomobartoli  thanks for the quick reply. I will give it a try and let you know. Thanks a lot

**Comment by di-jabil** [comment]
Hi I did some experiments and ran into some issues. I posted an issue here [https://github.com/google/aiyprojects-raspbian/issues/563](url). I would much appreciate if you could take a look and give me some comments. Thank you so much

**Comment by di-jabil** [comment]
Hi thanks a lot for your reply and input. I have made some progress on the issue. Please see here for details if you are interested https://github.com/google/aiyprojects-raspbian/issues/564

Again, much appreciate your help and advice

**Comment by giacomobartoli** [comment]
Ok, I am glad you solved the issue. Can I close the ticket now?

**Comment by di-jabil** [comment]
Yes please. Much appreciate your help and advice. Thank you
