### ISSUE TITLE
Which mobilenet model was used for the retraining purpose

### ISSUE THREAD

**Issue by abhinavrawat27** [giacomobartoli/vision-kit#4]
Hi

I tested the repo and it works fine. I have been following Tensorflow for Poets 2 tutorial and AIY vision kit makers guide to compile and run it but I have been facing issues like:

`aiy.vision.inference.InferenceException: UnloadModel: Model 'object_detection' is not loaded.`

But when I tested your repo, it worked out of the box. Just wanted to know which model you used and how you retrained it. It will be good if you can list out some steps.

Thanks

**Comment by giacomobartoli** [comment]
Hi,
I used an embedded_ssd_mobilenet, which is the only supported model for real time object detection on the Google Vision kit.

The pre-trained mode was based on Pascal Voc as dataset.

I hope this will help you. If you have other questions feel free to ask :-)

**Comment by abhinavrawat27** [comment]
Hi @giacomobartoli  , thanks for reply. Did you retrained your model on your local ubuntu machine or somewhere on cloud.
 I was following this tutorial https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/#3
where we need to mention `ARCHITECTURE`, which architecture name should I use. Can you please share the retrain command, it will be very helpfull. Thanks

**Comment by giacomobartoli** [comment]
I retrained the network on a private server provided by the university, but I would recommend you to buy some gpus on aws, floydhub, etc. It is almost impossible to train the model on your local machine.

I installed tensorflow [object detection apis](https://github.com/tensorflow/models/tree/master/research/object_detection), following these [istructions](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/configuring_jobs.md). Once I obtained the tf frozen graph, I compiled it on a local VM with ubuntu 14.04. The protobinary file is what the Vision Kit is able to read.

**Comment by abhinavrawat27** [comment]
Hi, I have been able to train one of the model. I did this just to get an overall idea about transfer learning.
Now I want to train the embedded ssd model for AIY kit but I am not able to find this on [tensorflow model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md). Which model should I select. 

As per my understanding I can go with ssd_mobilenet_v1_coco model and use embedded_ssd_modbilenet.config file. Is that right.? Please correct me if I am wrong.

**Comment by giacomobartoli** [comment]
@abhinavrawat27 Unfortunately, there is no pre-trained model for embedded_ssd_mobilenet.
Google does not provide it on their website ([model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md)). However, I found someone on the web who shared a pre-trained model (embedded_ssd_mobilenet) on Pascal-Voc dataset. It is pre-trained on Voc, so do not expect great performances such as other detectors trained on imagenet or Coco (pascal voc has only 20 classes), but it is still a good starting point for personal projects. [This is](https://drive.google.com/file/d/1_MeZ8kvmpNibPZvSJGnwKNRATeuyxNtu/view) the one I used for the Pikachu real time detector.
Given this pre-trained model (.ckpt), you can you use the embedded_ssd_mobilenet.config for starting the training and apply transfer learning for creating your custom model.

**Comment by abhinavrawat27** [comment]
@giacomobartoli Thanks for the models. When you say Voc data set, does that mean that I can not use the [embedded_ssd_mobilenet_v1_coco.config](https://github.com/tensorflow/models/blob/master/research/object_detection/samples/configs/embedded_ssd_mobilenet_v1_coco.config) file as it is based on coco dataset. I am not able to find the correct voc data set file. Can you please share the config file. Thanks

**Comment by abhinavrawat27** [comment]
@giacomobartoli I found your discussion on this [link](https://github.com/google/aiyprojects-raspbian/issues/446) and it looks like we cannot use coco config file of embedded mobilenet . Please confirm and correct me if I am wrong. 
Can you please share your config file. It will be very helpful. Thanks

**Comment by giacomobartoli** [comment]
@abhinavrawat27 sorry for being late, but I was super busy during these days!
Anyway.. you can use even coco config file, just replace the fields according to tf object detection APIs. This was my config file. Let me know if you have other doubts!
(It's a txt file, but you must rename it to .config. I did this conversion so that I could upload the file on github attach to this issue).

Do not forget to uncomment the 'fine-tuning' line. This is the only way to apply transfer learning.

[embedded_ssd_mobilenet_v1_coco.txt](https://github.com/giacomobartoli/vision-kit/files/2902894/embedded_ssd_mobilenet_v1_coco.txt)

**Comment by abhinavrawat27** [comment]
Thanks @giacomobartoli I used your config file and the model provided by you. Dont know why it throws error `ValueError: No variables to save`. Below is the command I used:

`python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/embedded_ssd_mobilenet_v1_coco.config`

output is attached. Do you have any idea why its throwing this error.
[Error.txt](https://github.com/giacomobartoli/vision-kit/files/2903808/Error.txt)

**Comment by giacomobartoli** [comment]
@abhinavrawat27 which version of tensorflow obj detection APIs are you using?

**Comment by voss01** [comment]
I'm having the same issue and I'm using the newest API. Did you used the same exact config file to run your training, and this command:  `python3 train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/embedded_ssd_mobilenet_v1_coco.config` ? It would really help me if you have a solution

**Comment by giacomobartoli** [comment]
Yes, but without specifying python3.

**Comment by voss01** [comment]
Ok I’m going to try it like that
